"""Data models for Threat Indexing (T_index) calculation and risk assessment."""

from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class RiskTier(str, Enum):
    """Categorized risk tiers based on T_index severity."""

    LOW = "LOW"          # 0 <= T_index < 40: Automated scam filtering / citizen advisory
    MEDIUM = "MEDIUM"    # 40 <= T_index < 70: Case logged, verification triggered, patrol alert
    HIGH = "HIGH"        # 70 <= T_index <= 100: Critical extortion, immediate tactical dispatch


class ThreatFactorScores(BaseModel):
    """Individual normalized factor scores (0.0 to 100.0)."""

    coercion: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Physical threat level, family danger, weapon mentions, immediacy of harm.",
    )
    persistence: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Frequency of harassment, cross-platform contacts, escalation timeline.",
    )
    artifacts: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Verifiable forensic data: bank accounts, phone numbers, crypto wallets, voice matches.",
    )
    vulnerability: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Target profile vulnerability: elderly, minors, isolated businesses, fear index.",
    )


class ThreatIndexResult(BaseModel):
    """Complete computed Dynamic Extortion Threat Index assessment."""

    t_index: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Final weighted quantitative score (0-100).",
    )
    tier: RiskTier = Field(
        ...,
        description="Calculated risk tier.",
    )
    factor_scores: ThreatFactorScores = Field(
        ...,
        description="Individual factor score breakdown.",
    )
    factor_weights: Dict[str, float] = Field(
        ...,
        description="Applied weights per factor.",
    )
    reasoning: str = Field(
        ...,
        description="Cognitive rationale behind the score generated by Gemini.",
    )
    recommended_actions: List[str] = Field(
        default_factory=list,
        description="Action items for institutional operators and citizen protection.",
    )
    confidence_score: float = Field(
        default=0.95,
        ge=0.0,
        le=1.0,
        description="Model confidence level in forensic evaluation.",
    )
